version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaprojectaws2024 -Dsonar.organization=javaprojectaws2024 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=f44349f22558f00cb379c2a6f7cb653b02f10851
